spring:

  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8088
  cloud:
    gateway:
     routes:
       - id: authentification
         uri: lb://authentification
         predicates:
          - Path=/api/users/**
         filters:
          - StripPrefix=1
       - id: prayertime
         uri: localhost:8083
         predicates:
           - Path=/api/prayers/**
         filters:
           - StripPrefix=1

       - id: service2
         predicates:
           - Path=/demo/**
         uri: http://localhost:9098
server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


