apiVersion: v1
kind: ConfigMap
metadata:
  name: export-sql-configmap
data:
  export.sql: |
    --
    -- PostgreSQL database dump
    --

    -- Dumped from database version 16.2
    -- Dumped by pg_dump version 16.2

 


    SET statement_timeout = 0;
    SET lock_timeout = 0;
    SET idle_in_transaction_session_timeout = 0;
    SET client_encoding = 'UTF8';
    SET standard_conforming_strings = on;
    SELECT pg_catalog.set_config('search_path', '', false);
    SET check_function_bodies = false;
    SET xmloption = content;
    SET client_min_messages = warning;
    SET row_security = off;

    SET default_tablespace = '';

    SET default_table_access_method = heap;

    --
    -- TOC entry 232 (class 1259 OID 16461)
    -- Name: prayer; Type: TABLE; Schema: public; Owner: postgres   
    --

    CREATE TABLE public.prayer (
    id integer NOT NULL,
    id_region integer,
    "يوم" character varying(20),
    "الهجري" character varying(10),
    "الميلادي" date,
    "الامساك" character varying(10),
    "الفجر" character varying(10),
    "الشروق" character varying(10),
    "الظهر" character varying(10),
    "العصر" character varying(10),
    "المغرب" character varying(10),
    "العشاء" character varying(10)
    );


    ALTER TABLE public.prayer OWNER TO postgres;

    --
    -- TOC entry 233 (class 1259 OID 16464)
    -- Name: prayer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --

    CREATE SEQUENCE public.prayer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


    ALTER SEQUENCE public.prayer_id_seq OWNER TO postgres;

    --
    -- TOC entry 4868 (class 0 OID 0)
    -- Dependencies: 233
    -- Name: prayer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
    --

    ALTER SEQUENCE public.prayer_id_seq OWNED BY public.prayer.id;


    --
    -- TOC entry 237 (class 1259 OID 16474)
    -- Name: regions; Type: TABLE; Schema: public; Owner: postgres
    --

    CREATE TABLE public.regions (
    id_region integer NOT NULL,
    nom character varying(100) NOT NULL
    );


    ALTER TABLE public.regions OWNER TO postgres;

    --
    -- TOC entry 238 (class 1259 OID 16477)
    -- Name: regions_id_region_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --

    CREATE SEQUENCE public.regions_id_region_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


    ALTER SEQUENCE public.regions_id_region_seq OWNER TO postgres;

    --
    -- TOC entry 4869 (class 0 OID 0)
    -- Dependencies: 238
    -- Name: regions_id_region_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
    --

    ALTER SEQUENCE public.regions_id_region_seq OWNED BY public.regions.id_region;


    --
    -- TOC entry 4709 (class 2604 OID 16533)
    -- Name: prayer id; Type: DEFAULT; Schema: public; Owner: postgres
    --

    ALTER TABLE ONLY public.prayer ALTER COLUMN id SET DEFAULT nextval('public.prayer_id_seq'::regclass);


    --
    -- TOC entry 4710 (class 2604 OID 16535)
    -- Name: regions id_region; Type: DEFAULT; Schema: public; Owner: postgres
    --

    ALTER TABLE ONLY public.regions ALTER COLUMN id_region SET DEFAULT nextval('public.regions_id_region_seq'::regclass);


    --
    -- TOC entry 4859 (class 0 OID 16461)
    -- Dependencies: 232
    -- Data for Name: prayer; Type: TABLE DATA; Schema: public; Owner: postgres 
    --

    INSERT INTO public.prayer VALUES (1, 1, 'الاثنين', '1', '2024-03-11', '4:59', '5:09', '6:35', '12:29', '3:50', '6:23', '7:44');
    INSERT INTO public.prayer VALUES (2, 1, 'الثلاثاء', '2', '2024-03-12', '4:58', '5:08', '6:34', '12:29', '3:50', '6:24', '7:45');
    INSERT INTO public.prayer VALUES (3, 1, 'الاربعاء', '3', '2024-03-13', '4:56', '5:06', '6:33', '12:28', '3:51', '6:25', '7:46');
    INSERT INTO public.prayer VALUES (4, 1, 'الخميس', '4', '2024-03-14', '4:55', '5:05', '6:31', '12:28', '3:51', '6:26', '7:47');
    INSERT INTO public.prayer VALUES (5, 1, 'الجمعة', '5', '2024-03-15', '4:53', '5:03', '6:30', '12:28', '3:51', '6:27', '7:48');
    INSERT INTO public.prayer VALUES (6, 1, 'السبت', '6', '2024-03-16', '4:52', '5:02', '6:28', '12:28', '3:52', '6:28', '7:49');
    INSERT INTO public.prayer VALUES (7, 1, 'الاحد', '7', '2024-03-17', '4:50', '5:00', '6:27', '12:27', '3:52', '6:29', '7:50');
    INSERT INTO public.prayer VALUES (8, 1, 'الاثنين', '8', '2024-03-18', '4:49', '4:59', '6:25', '12:27', '3:53', '6:29', '7:51');
    INSERT INTO public.prayer VALUES (9, 1, 'الثلاثاء', '9', '2024-03-19', '4:47', '4:57', '6:24', '12:27', '3:53', '6:30', '7:52');
    INSERT INTO public.prayer VALUES (10, 1, 'الاربعاء', '10', '2024-03-20', '4:46', '4:56', '6:22', '12:26', '3:53', '6:31', '7:53');
    INSERT INTO public.prayer VALUES (11, 1, 'الخميس', '11', '2024-03-21', '4:44', '4:54', '6:21', '12:26', '3:54', '6:32', '7:54');
    INSERT INTO public.prayer VALUES (12, 1, 'الجمعة', '12', '2024-03-22', '4:42', '4:52', '6:19', '12:26', '3:54', '6:33', '7:55');
    INSERT INTO public.prayer VALUES (13, 1, 'السبت', '13', '2024-03-23', '4:41', '4:51', '6:18', '12:26', '3:54', '6:34', '7:56');
    INSERT INTO public.prayer VALUES (14, 1, 'الاحد', '14', '2024-03-24', '4:39', '4:49', '6:16', '12:25', '3:55', '6:35', '7:57');
    INSERT INTO public.prayer VALUES (15, 1, 'الاثنين', '15', '2024-03-25', '4:38', '4:48', '6:15', '12:25', '3:55', '6:36', '7:58');
    INSERT INTO public.prayer VALUES (16, 1, 'الثلاثاء', '16', '2024-03-26', '4:36', '4:46', '6:13', '12:25', '3:55', '6:37', '7:59');
    INSERT INTO public.prayer VALUES (17, 1, 'الاربعاء', '17', '2024-03-27', '4:34', '4:44', '6:12', '12:24', '3:56', '6:37', '8:00');
    INSERT INTO public.prayer VALUES (18, 1, 'الخميس', '18', '2024-03-28', '4:33', '4:43', '6:10', '12:24', '3:56', '6:38', '8:01');
    INSERT INTO public.prayer VALUES (19, 1, 'الجمعة', '19', '2024-03-29', '4:31', '4:41', '6:09', '12:24', '3:56', '6:39', '8:02');
    INSERT INTO public.prayer VALUES (20, 1, 'السبت', '20', '2024-03-30', '4:29', '4:39', '6:07', '12:23', '3:57', '6:40', '8:03');
    INSERT INTO public.prayer VALUES (21, 1, 'الاحد', '21', '2024-03-31', '4:28', '4:38', '6:06', '12:23', '3:57', '6:41', '8:04');
    INSERT INTO public.prayer VALUES (22, 1, 'الاثنين', '22', '2024-04-01', '4:26', '4:36', '6:05', '12:23', '3:57', '6:42', '8:05');
    INSERT INTO public.prayer VALUES (23, 1, 'الثلاثاء', '23', '2024-04-02', '4:24', '4:34', '6:03', '12:23', '3:57', '6:43', '8:06');
    INSERT INTO public.prayer VALUES (24, 1, 'الاربعاء', '24', '2024-04-03', '4:23', '4:33', '6:02', '12:22', '3:58', '6:44', '8:07');
    INSERT INTO public.prayer VALUES (25, 1, 'الخميس', '25', '2024-04-04', '4:21', '4:31', '6:00', '12:22', '3:58', '6:44', '8:08');
    INSERT INTO public.prayer VALUES (26, 1, 'الجمعة', '26', '2024-04-05', '4:20', '4:30', '5:59', '12:22', '3:58', '6:45', '8:09');
    INSERT INTO public.prayer VALUES (27, 1, 'السبت', '27', '2024-04-06', '4:18', '4:28', '5:57', '12:21', '3:58', '6:46', '8:10');
    INSERT INTO public.prayer VALUES (28, 1, 'الاحد', '28', '2024-04-07', '4:16', '4:26', '5:56', '12:21', '3:59', '6:47', '8:11');
    INSERT INTO public.prayer VALUES (29, 1, 'الاثنين', '29', '2024-04-08', '4:15', '4:25', '5:54', '12:21', '3:59', '6:48', '8:12');
    INSERT INTO public.prayer VALUES (30, 1, 'الاثنين', '30', '2024-04-09', '4:15', '4:25', '5:54', '12:21', '3:59', '6:48', '8:12');
    INSERT INTO public.prayer VALUES (31, 1, 'الثلاثاء', '30', '2024-04-10', '4:15', '4:25', '5:54', '12:21', '3:59', '6:48', '8:12');
    INSERT INTO public.prayer VALUES (32, 2, 'الاثنين', '1', '2024-03-11', '4:59', '5:09', '6:35', '12:29', '3:50', '6:23', '7:44');
    INSERT INTO public.prayer VALUES (33, 2, 'الثلاثاء', '2', '2024-03-12', '4:58', '5:08', '6:34', '12:29', '3:50', '6:24', '7:45');
    INSERT INTO public.prayer VALUES (34, 2, 'الاربعاء', '3', '2024-03-13', '4:56', '5:06', '6:33', '12:28', '3:51', '6:25', '7:46');
    INSERT INTO public.prayer VALUES (35, 2, 'الخميس', '4', '2024-03-14', '4:55', '5:05', '6:31', '12:28', '3:51', '6:26', '7:47');
    INSERT INTO public.prayer VALUES (36, 2, 'الجمعة', '5', '2024-03-15', '4:53', '5:03', '6:30', '12:28', '3:51', '6:27', '7:48');
    INSERT INTO public.prayer VALUES (37, 2, 'السبت', '6', '2024-03-16', '4:52', '5:02', '6:28', '12:28', '3:52', '6:28', '7:49');
    INSERT INTO public.prayer VALUES (38, 2, 'الاحد', '7', '2024-03-17', '4:50', '5:00', '6:27', '12:27', '3:52', '6:29', '7:50');
    INSERT INTO public.prayer VALUES (39, 2, 'الاثنين', '8', '2024-03-18', '4:49', '4:59', '6:25', '12:27', '3:53', '6:29', '7:51');
    INSERT INTO public.prayer VALUES (40, 2, 'الثلاثاء', '9', '2024-03-19', '4:47', '4:57', '6:24', '12:27', '3:53', '6:30', '7:52');
    INSERT INTO public.prayer VALUES (41, 2, 'الاربعاء', '10', '2024-03-20', '4:46', '4:56', '6:22', '12:26', '3:53', '6:31', '7:53');
    INSERT INTO public.prayer VALUES (42, 2, 'الخميس', '11', '2024-03-21', '4:44', '4:54', '6:21', '12:26', '3:54', '6:32', '7:54');
    INSERT INTO public.prayer VALUES (43, 2, 'الجمعة', '12', '2024-03-22', '4:42', '4:52', '6:19', '12:26', '3:54', '6:33', '7:55');
    INSERT INTO public.prayer VALUES (44, 2, 'السبت', '13', '2024-03-23', '4:41', '4:51', '6:18', '12:26', '3:54', '6:34', '7:56');
    INSERT INTO public.prayer VALUES (45, 2, 'الاحد', '14', '2024-03-24', '4:39', '4:49', '6:16', '12:25', '3:55', '6:35', '7:57');
    INSERT INTO public.prayer VALUES (46, 2, 'الاثنين', '15', '2024-03-25', '4:38', '4:48', '6:15', '12:25', '3:55', '6:36', '7:58');
    INSERT INTO public.prayer VALUES (47, 2, 'الثلاثاء', '16', '2024-03-26', '4:36', '4:46', '6:13', '12:25', '3:55', '6:37', '7:59');
    INSERT INTO public.prayer VALUES (48, 2, 'الاربعاء', '17', '2024-03-27', '4:34', '4:44', '6:12', '12:24', '3:56', '6:37', '8:00');
    INSERT INTO public.prayer VALUES (49, 2, 'الخميس', '18', '2024-03-28', '4:33', '4:43', '6:10', '12:24', '3:56', '6:38', '8:01');
    INSERT INTO public.prayer VALUES (50, 2, 'الجمعة', '19', '2024-03-29', '4:31', '4:41', '6:09', '12:24', '3:56', '6:39', '8:02');
    INSERT INTO public.prayer VALUES (51, 2, 'السبت', '20', '2024-03-30', '4:29', '4:39', '6:07', '12:23', '3:57', '6:40', '8:03');
    INSERT INTO public.prayer VALUES (52, 2, 'الاحد', '21', '2024-03-31', '4:28', '4:38', '6:06', '12:23', '3:57', '6:41', '8:04');
    INSERT INTO public.prayer VALUES (53, 2, 'الاثنين', '22', '2024-04-01', '4:26', '4:36', '6:05', '12:23', '3:57', '6:42', '8:05');
    INSERT INTO public.prayer VALUES (54, 2, 'الثلاثاء', '23', '2024-04-02', '4:24', '4:34', '6:03', '12:23', '3:57', '6:43', '8:06');
    INSERT INTO public.prayer VALUES (55, 2, 'الاربعاء', '24', '2024-04-03', '4:23', '4:33', '6:02', '12:22', '3:58', '6:44', '8:07');
    INSERT INTO public.prayer VALUES (56, 2, 'الخميس', '25', '2024-04-04', '4:21', '4:31', '6:00', '12:22', '3:58', '6:44', '8:08');
    INSERT INTO public.prayer VALUES (57, 2, 'الجمعة', '26', '2024-04-05', '4:20', '4:30', '5:59', '12:22', '3:58', '6:45', '8:09');
    INSERT INTO public.prayer VALUES (58, 2, 'السبت', '27', '2024-04-06', '4:18', '4:28', '5:57', '12:21', '3:58', '6:46', '8:10');
    INSERT INTO public.prayer VALUES (59, 2, 'الاحد', '28', '2024-04-07', '4:16', '4:26', '5:56', '12:21', '3:59', '6:47', '8:11');
    INSERT INTO public.prayer VALUES (60, 2, 'الاثنين', '29', '2024-04-08', '4:15', '4:25', '5:54', '12:21', '3:59', '6:48', '8:12');
    INSERT INTO public.prayer VALUES (61, 2, 'الاثنين', '30', '2024-04-09', '4:15', '4:25', '5:54', '12:21', '3:59', '6:48', '8:12');
    INSERT INTO public.prayer VALUES (62, 2, 'الثلاثاء', '30', '2024-04-10', '4:15', '4:25', '5:54', '12:21', '3:59', '6:48', '8:12');
    INSERT INTO public.prayer VALUES (63, 3, 'الاثنين', '1', '2024-03-11', '4:59', '5:09', '6:35', '12:29', '3:50', '6:23', '7:44');
    INSERT INTO public.prayer VALUES (64, 3, 'الثلاثاء', '2', '2024-03-12', '4:58', '5:08', '6:34', '12:29', '3:50', '6:24', '7:45');
    INSERT INTO public.prayer VALUES (65, 3, 'الاربعاء', '3', '2024-03-13', '4:56', '5:06', '6:33', '12:28', '3:51', '6:25', '7:46');
    INSERT INTO public.prayer VALUES (66, 3, 'الخميس', '4', '2024-03-14', '4:55', '5:05', '6:31', '12:28', '3:51', '6:26', '7:47');
    INSERT INTO public.prayer VALUES (67, 3, 'الجمعة', '5', '2024-03-15', '4:53', '5:03', '6:30', '12:28', '3:51', '6:27', '7:48');
    INSERT INTO public.prayer VALUES (68, 3, 'السبت', '6', '2024-03-16', '4:52', '5:02', '6:28', '12:28', '3:52', '6:28', '7:49');
    INSERT INTO public.prayer VALUES (69, 3, 'الاحد', '7', '2024-03-17', '4:50', '5:00', '6:27', '12:27', '3:52', '6:29', '7:50');
    INSERT INTO public.prayer VALUES (70, 3, 'الاثنين', '8', '2024-03-18', '4:49', '4:59', '6:25', '12:27', '3:53', '6:29', '7:51');
    INSERT INTO public.prayer VALUES (71, 3, 'الثلاثاء', '9', '2024-03-19', '4:47', '4:57', '6:24', '12:27', '3:53', '6:30', '7:52');
    INSERT INTO public.prayer VALUES (72, 3, 'الاربعاء', '10', '2024-03-20', '4:46', '4:56', '6:22', '12:26', '3:53', '6:31', '7:53');
    INSERT INTO public.prayer VALUES (73, 3, 'الخميس', '11', '2024-03-21', '4:44', '4:54', '6:21', '12:26', '3:54', '6:32', '7:54');
    INSERT INTO public.prayer VALUES (74, 3, 'الجمعة', '12', '2024-03-22', '4:42', '4:52', '6:19', '12:26', '3:54', '6:33', '7:55');
    INSERT INTO public.prayer VALUES (75, 3, 'السبت', '13', '2024-03-23', '4:41', '4:51', '6:18', '12:26', '3:54', '6:34', '7:56');
    INSERT INTO public.prayer VALUES (76, 3, 'الاحد', '14', '2024-03-24', '4:39', '4:49', '6:16', '12:25', '3:55', '6:35', '7:57');
    INSERT INTO public.prayer VALUES (77, 3, 'الاثنين', '15', '2024-03-25', '4:38', '4:48', '6:15', '12:25', '3:55', '6:36', '7:58');
    INSERT INTO public.prayer VALUES (78, 3, 'الثلاثاء', '16', '2024-03-26', '4:36', '4:46', '6:13', '12:25', '3:55', '6:37', '7:59');
    INSERT INTO public.prayer VALUES (79, 3, 'الاربعاء', '17', '2024-03-27', '4:34', '4:44', '6:12', '12:24', '3:56', '6:37', '8:00');
    INSERT INTO public.prayer VALUES (80, 3, 'الخميس', '18', '2024-03-28', '4:33', '4:43', '6:10', '12:24', '3:56', '6:38', '8:01');
    INSERT INTO public.prayer VALUES (81, 3, 'الجمعة', '19', '2024-03-29', '4:31', '4:41', '6:09', '12:24', '3:56', '6:39', '8:02');
    INSERT INTO public.prayer VALUES (82, 3, 'السبت', '20', '2024-03-30', '4:29', '4:39', '6:07', '12:23', '3:57', '6:40', '8:03');
    INSERT INTO public.prayer VALUES (83, 3, 'الاحد', '21', '2024-03-31', '4:28', '4:38', '6:06', '12:23', '3:57', '6:41', '8:04');
    INSERT INTO public.prayer VALUES (84, 3, 'الاثنين', '22', '2024-04-01', '4:26', '4:36', '6:05', '12:23', '3:57', '6:42', '8:05');
    INSERT INTO public.prayer VALUES (85, 3, 'الثلاثاء', '23', '2024-04-02', '4:24', '4:34', '6:03', '12:23', '3:57', '6:43', '8:06');
    INSERT INTO public.prayer VALUES (86, 3, 'الاربعاء', '24', '2024-04-03', '4:23', '4:33', '6:02', '12:22', '3:58', '6:44', '8:07');
    INSERT INTO public.prayer VALUES (87, 3, 'الخميس', '25', '2024-04-04', '4:21', '4:31', '6:00', '12:22', '3:58', '6:44', '8:08');
    INSERT INTO public.prayer VALUES (88, 3, 'الجمعة', '26', '2024-04-05', '4:20', '4:30', '5:59', '12:22', '3:58', '6:45', '8:09');
    INSERT INTO public.prayer VALUES (89, 3, 'السبت', '27', '2024-04-06', '4:18', '4:28', '5:57', '12:21', '3:58', '6:46', '8:10');
    INSERT INTO public.prayer VALUES (90, 3, 'الاحد', '28', '2024-04-07', '4:16', '4:26', '5:56', '12:21', '3:59', '6:47', '8:11');
    INSERT INTO public.prayer VALUES (91, 3, 'الاثنين', '29', '2024-04-08', '4:15', '4:25', '5:54', '12:21', '3:59', '6:48', '8:12');
    INSERT INTO public.prayer VALUES (92, 3, 'الاثنين', '30', '2024-04-09', '4:15', '4:25', '5:54', '12:21', '3:59', '6:48', '8:12');
    INSERT INTO public.prayer VALUES (93, 3, 'الثلاثاء', '30', '2024-04-10', '4:15', '4:25', '5:54', '12:21', '3:59', '6:48', '8:12');


    --
    -- TOC entry 4861 (class 0 OID 16474)
    -- Dependencies: 237
    -- Data for Name: regions; Type: TABLE DATA; Schema: public; Owner: postgres
    --

    INSERT INTO public.regions VALUES (1, 'tozeur');
    INSERT INTO public.regions VALUES (2, 'nefta');
    INSERT INTO public.regions VALUES (3, 'tamerza');
    INSERT INTO public.regions VALUES (4, 'hemma');
    INSERT INTO public.regions VALUES (5, 'dgeche');


    --
    -- TOC entry 4870 (class 0 OID 0)
    -- Dependencies: 233
    -- Name: prayer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --

    SELECT pg_catalog.setval('public.prayer_id_seq', 93, true);


    --
    -- TOC entry 4871 (class 0 OID 0)
    -- Dependencies: 238
    -- Name: regions_id_region_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --

    SELECT pg_catalog.setval('public.regions_id_region_seq', 5, true);


    --
    -- TOC entry 4712 (class 2606 OID 16569)
    -- Name: prayer prayer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --

    ALTER TABLE ONLY public.prayer
      ADD CONSTRAINT prayer_pkey PRIMARY KEY (id);


    --
    -- TOC entry 4714 (class 2606 OID 16573)
    -- Name: regions regions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --

    ALTER TABLE ONLY public.regions
        ADD CONSTRAINT regions_pkey PRIMARY KEY (id_region);


    --
    -- TOC entry 4715 (class 2606 OID 16605)
    -- Name: prayer prayer_id_region_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --

    ALTER TABLE ONLY public.prayer
        ADD CONSTRAINT prayer_id_region_fkey FOREIGN KEY (id_region) REFERENCES public.regions(id_region);


    -- Completed on 2024-06-09 20:58:36

    --
    -- PostgreSQL database dump complete
    --

